name: Deploy Github IO

on:
  push:
    branches:
      - source
  workflow_dispatch:

jobs:
  cancel_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: t-actions/cancel-actions@master
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Deploy
        run: |
          npm install -g hexo-cli
          npm install
          hexo g

          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

          cd public
          git init
          git add .
          git commit -m "Site Updated: $(date +%Y-%m-%d.%H:%M:%S)"
          git remote add origin https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}
          git push origin HEAD:master -f